# 路径: configs/train_dppo.yaml

# 🌟 核心：告诉 Hydra 去哪里拉取基础配置
defaults:
  - _self_                      # 允许本文件覆盖上面的默认值
  - policy: ft_zed_diffusion   

resume: false
resume_path: none
device: "cuda:0"  # cuda或cpu

hydra:
  run:
    dir: outputs/finetune/train/${now:%Y-%m-%d}/${now:%H-%M-%S}_${env.task}_${hydra.runtime.choices.policy}
    # dir: src/av-aloha/DPPO/outputs/pretrain/train/${now:%Y-%m-%d}/${now:%H-%M-%S}_${env.name}_${policy.name}_${hydra.job.name}
  job:
    name: ${env.task}_${hydra.runtime.choices.policy}_${now:%Y-%m-%d}_${now:%H-%M-%S}

training:
  pretrained_ckpt_path: "outputs/pretrain/train/.../checkpoints/050000"
  min_sampling_denoising_std: 0.02  # 为 DDIM 采样注入的动作探索标准差，越大越随机，越小越稳定
  min_logprob_denoising_std: 0.08  # 控制概率计算分母，过大会导致KL爆炸
  reward_ema_alpha: 0.02 #滑动更新全局奖励方差
  target_kl: 0.02
  lr_backbone: 1e-5
  use_disk_cache: True   # True 开启硬盘缓存 (省内存), False 开启纯内存模式 (速度最快)

eval:
  checkpoint_metric: "reward" # 筛选指标：可选 'loss' 或 'reward'
  max_checkpoints: 10  # 最多保存loss最小的几个模型快照
  n_episodes: 10             # 每次评估跑多少个完整的 episode
  max_episodes_rendered: 1   # 最多保存前几个 episode 的录像视频
  records_resume: True  # 是否读取top-k的快照和视频列表 即top_k_records.json
  fps: 25                    # 录制的 MP4 视频帧率

wandb:
  enable: true
  # Set to true to disable saving an artifact despite save_checkpoint == True
  disable_artifact: true # 不保存artifact，即不上传权重模型
  project: ${env.task}_finetune  #项目名称
  notes: ""
  save_code: false  # 是否保存代码

seed: ???